name: "Issues from todo comments"

on:
  push:
    branches:
      - main

jobs:
  todo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2.3.4"
      
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@541150182ae0d5d4fd891839af0063192a6f4504"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
