name: "Issues from todo comments"

on:
  push:
    branches:
      - main

jobs:
  todo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@269ec385ab1e0b62a35cb410649c4bcbdaf5f97b"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
