name: "Issues from todo comments"

on:
  push:
    branches:
      - main

jobs:
  todo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2.3.4"
      
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@70d10efd53a64c110938ec7d44ff36a045be76b4"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
