name: "Issues from todo comments"

on:
  push:
    branches:
      - main

jobs:
  todo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2.4.0"
      
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@283da1a7ccac0b53226d06d6f7826f785e06e3d2"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
