name: "Issues from todo comments"

on:
  push:
    branches:
      - main

jobs:
  todo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2.4.0"
      
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@d9c37e1813f8bc43e79905a54a0c47dcbb315dcc"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
